baseURL = "https://sleepyalex.ca"
languageCode = "en-us"
title = "Alex's Notebook"
enableGitInfo = true

[taxonomies]
   tag = "tags"
   category = "categories"

hasCJKLanguage = true
[permalinks]
   posts = "/posts/:title/"

[frontmatter]
   date=['date', 'publishDate', 'lastmod']
   lastmod = [':git', 'lastmod', 'date', 'publishDate']
   publishDate = ['publishDate', 'date']

[module]
[[module.imports]]
  # path = "github.com/spf13/hyde"
  # path = "github.com/vimux/blank"
  path = "github.com/alexhyang/blank"

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
[markup] 
   [highlight]
      guessSyntax = true
      style = "emacs"


# Social links in footer, support github,twitter,stackoverflow,facebook
[social]
   # e.g.
   # github = "https://github.com/alexhyang"
   # twitter: your-github-link
   # stackoverflow: your-github-link
   # facebook: your-facebook-link


# Site parameters
# Sidebar menus
[[menus]]
[[menu.main]]
    name = "Home"
    url = "/"
    Weight = -1
[[menu.main]]
    name = "Archives"
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]
   # Site Author
   author = "Alex Yang"
   # Author biography
   bio = ""
   # Site Description, used in HTML meat
   description = "Personal Research Notebook"
   enableRSS = true
   # To enable comments, you may need to set `disqusShortname`
   enableComments = false
   # To enable comments, you may need to set `googleAnalytics`
   enableGoogleAnalytics = true
   themeColor = "theme-base-0d"
