baseURL = "http://alexhyang.github.io"
languageCode = "en-us"
title = "Alex Yang"
[taxonomies]
   tag = "tags"
   category = "categories"

hasCJKLanguage = true
[permalinks]
   posts = "/posts/:title/"

[module]
[[module.imports]]
  path = "github.com/spf13/hyde"

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
[markup] 
   [highlight]
      guessSyntax = true
      style = "emacs"


# Social links in footer, support github,twitter,stackoverflow,facebook
[social]
   # e.g.
   github = "https://github.com/alexhyang"
   # twitter: your-github-link
   # stackoverflow: your-github-link
   # facebook: your-facebook-link


# Site parameters
[params]
   # Site Author
   author = "Alex Yang"
   # Author biography
   bio = "Full Stack Engineer"
   # Site Description, used in HTML meat
   description = "Some Tech Notes"
   enableRSS = false
   # To enable comments, you may need to set `disqusShortname`
   enableComments = false
   # To enable comments, you may need to set `googleAnalytics`
   enableGoogleAnalytics = false
